name: Create and check package
description: building, checking the package

inputs:
  pkg-name:
    description: package name inside lightning.*
    required: true

runs:
  using: "composite"
  steps:

  - name: install dev. env
    run: pip install "twine==4.0.1" setuptools wheel flake8
    shell: bash

  - name: Create package
    env:
      PACKAGE_NAME: ${{ inputs.pkg-name }}
    run: |
      python setup.py check --metadata --strict
      flake8 src/lightning/ --ignore E402,F401,E501,W391,E303
      python setup.py sdist bdist_wheel
    shell: bash

  - name: Check package
    run: |
      ls -l dist/
      twine check dist/*
      # python setup.py clean
    shell: bash

  - name: copy/export pkg
    run: cp dist/* pypi/
    shell: bash
